config/routes.rb
Rails.application.routes.draw do
  get '/:sitemap', to:          'sitemaps#show',
                   constraints: { format: /xml/, sitemap: /sitemap-.+/ }
  require 'sidekiq/web'
  get '/robots.:format', to: 'pages#robots'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :embed, only: :update
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all

    unauthenticated do
      root 'explore#index'
    end

    authenticated :user do
      root 'pins#index', as: :authenticated_root
    end
    get 'terms_of_use' => 'pages#terms_of_use'
    get 'privacy_policy' => 'pages#privacy_policy'
    get 'about' => 'pages#about'
    get 'cookie_policy' => 'pages#cookie_policy'
    devise_for :users, skip: %i[registrations omniauth_callbacks]
    # devise/registrations#edit route'unu iptal etmek için aşağıdaki block eklendi
    as :user do
      get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get 'users/sign_up' => 'devise/registrations#new', as: 'new_user_registration'
      patch 'users' => 'devise/registrations#update', as: 'user_registration'
      put 'users' => 'devise/registrations#update'
      delete 'users' => 'devise/registrations#destroy'
      post 'users' => 'devise/registrations#create'
    end
    # search
    get 'search/pins'
    get 'search/boards'
    get 'search/users'
    # explore
    get 'explore/index'
    get 'explore/locations/:token' => 'explore#location', as: :explore_location
    # settings
    get 'settings/edit_profile'
    get 'settings/change_password'
    get 'settings/change_username'
    get 'settings/change_email'
    get 'settings/switch_locale'
    get 'settings/accept_cookies'
    namespace :settings do
      put 'profiles/update'
      put 'users/change_password'
      put 'users/change_username'
      put 'users/change_email'
    end
    resources :boards do
      member do
        get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
        get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
        get 'follow'
        get 'unfollow'
        patch 'move/:pin_id', action: 'move', as: 'move_pin'
        patch 'move_board_by_id'
        patch 'move_board_section/:board_section_id', action: 'move_board_section',
                                                      as:     'move_board_section'
        get 'add_to_board_section_list'
        get 'select_boards'
        get 'autocomplete'
        get 'merge'
      end
      collection do
        get 'add_to_board_list/:pin_id', action: 'add_to_board_list', as: 'add_to_board_list'
        get 'following_boards'
      end
      resources :board_sections, shallow: true, except: %i[index] do
        member do
          get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
          get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
          patch 'move'
          patch 'move_pin/:pin_id', action: 'move_pin', as: 'move_pin'
          get 'select_board_sections'
          get 'autocomplete'
          get 'merge'
        end
      end
    end
    resources :tags, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
      end
      collection do
        get 'following_tags'
      end
    end
    resources :profiles, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
        get 'followers'
        get 'following'
        get 'boards'
      end
    end
    resources :pins do
      member do
        get 'like'
        get 'unlike'
        get 'boards_added_by_owner'
      end
      collection do
        get 'liked_pins'
      end
    end
  end
end

app/models/pin.rb
# frozen_string_literal: true

class Pin < ApplicationRecord
  extend FriendlyId
  include ActiveRecord::Searchable

  acts_as_taggable_on :tags
  acts_as_votable
  geocoded_by :address do |obj, results|
    if results.present?
      obj.latitude = results.first.latitude
      obj.longitude = results.first.longitude
    else
      obj.latitude = nil
      obj.longitude = nil
    end
  end

  # secure_token
  has_secure_token

  # friendly_id
  friendly_id :name, use: :history

  # delegates
  delegate :username, to: :user, prefix: true

  # callbacks
  before_validation :geocode, if: ->(obj) { obj.address.present? && obj.address_changed? }
  before_validation :fix_tags, if: :tag_list_changed?
  before_save :set_caches
  before_update :delete_user_tags, prepend: true
  before_destroy :delete_crops
  before_destroy :delete_user_tags, prepend: true

  # relations
  has_one :cover_photo_crop, as: :cropable, class_name: 'Crop', dependent: :destroy
  accepts_nested_attributes_for :cover_photo_crop, update_only: true
  has_one_attached :cover_photo
  has_rich_text :description
  belongs_to :user
  has_many :pin_boards, dependent: :destroy
  has_many :boards, -> { order 'pin_boards.position ASC' }, through: :pin_boards, dependent: :destroy
  has_many :pin_board_sections, dependent: :destroy
  has_many :board_sections, lambda {
                              order 'pin_board_sections.position ASC'
                            }, through: :pin_board_sections, dependent: :destroy

  # validations
  validates :name, presence: true, length: { maximum: 128 }
  validates :cover_photo_description, length: { maximum: 500 }
  validates :address, presence: true
  validate :found_address_presence?, if: ->(obj) { obj.address.present? && obj.address_changed? }
  validate :max_tag_count, if: :tag_list_changed?
  validate :max_tag_length, if: :tag_list_changed?
  validate :description_length
  validate :max_number_of_description_attachments

  # counter_cultures
  counter_culture :user

  def cover_photo_crop_constraints
    return {} if cover_photo_crop.blank?

    {
      height: cover_photo_crop.crop_height.to_i,
      width:  cover_photo_crop.crop_width.to_i,
      x:      cover_photo_crop.crop_x.to_i,
      y:      cover_photo_crop.crop_y.to_i,
      crop:   'crop'
    }
  end

  def city_country
    address.split(',').last(2).join(',').strip
  end

  def owner_public_boards
    board_ids = boards.where(user:, privacy: 'public').ids
    board_ids_from_sections = board_sections.joins(board: :user)
                                            .where(boards: { users: { id: user }, privacy: 'public' })
                                            .pluck(:board_id)
    Board.where(id: board_ids | board_ids_from_sections).order(created_at: :desc)
  end

  def added_to_boards?(added_user = user)
    return true if pin_boards.joins(board: :user).where(users: { id: added_user }).any?

    pin_board_sections.joins(board_section: [board: :user]).where(users: { id: added_user }).any?
  end

  private

  def delete_crops
    return if cover_photo_crop.blank?

    cover_photo_crop.destroy
  end

  def found_address_presence?
    return if latitude.present? && longitude.present?

    errors.add(:address, :invalid)
  end

  def fix_tags
    tag_list_downcased = tag_list.to_s.downcase(:turkic)
    self.tag_list = tag_list_downcased.gsub(/[^a-z0-9,öçğışü]/, '').split(',')
  end

  def max_tag_count
    return if tag_list.count <= 5

    errors.add(:tag_list, :max_tag_count)
  end

  def max_tag_length
    return if tag_list.collect(&:length).max <= 30

    errors.add(:tag_list, :max_tag_length)
  end

  def delete_user_tags
    UserTag.where(tag: tags.where(taggings_count: 1)).destroy_all
  end

  def set_caches
    self.cached_tag_list = tag_list.to_s
    self.cached_plain_text_description = description&.body&.to_plain_text
    return if user.blank?

    self.cached_user_username = user_username
  end

  def should_generate_new_friendly_id?
    name.present? && name_changed?
  end

  def description_length
    return if description.body.blank?
    return if description.body.to_plain_text.length <= 5000

    errors.add(:description, :too_long, **{ count: 5000 })
  end

  def max_number_of_description_attachments
    return if description.body.blank?
    return if description.body
                         .attachments
                         .count { |a| !a.attachable.instance_of?(::Embed) } <= 6

    errors.add(:description, :max_number_of_description_attachments)
  end
end

app/controllers/pins_controller.rb
# frozen_string_literal: true

class PinsController < ApplicationController
  include Pagy::Backend
  before_action :set_pin, only: %i[show edit update destroy like unlike boards_added_by_owner]
  before_action :authenticate_user!, except: %i[show boards_added_by_owner]
  before_action :authorize_pin, except: %i[index show boards_added_by_owner]

  # GET /pins or /pins.json
  def index
    @pagy, @pins = pagy_pins_latest(items: 10)
    respond_to do |f|
      f.html
      f.turbo_stream
    end
  end

  # GET /pins/1 or /pins/1.json
  def show; end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit; end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: t('.success') }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: t('.success') }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: t('.success') }
      format.json { head :no_content }
      flash.now[:notice] = t('.success')
      format.turbo_stream
    end
  end

  def like
    @pin.liked_by current_user
  end

  def unlike
    @pin.unliked_by current_user
  end

  def liked_pins
    pin_ids = current_user.votes.where(votable_type: 'Pin').pluck(:votable_id)
    @pagy, @pins = pagy Pin.where(id: pin_ids).order(created_at: :desc)
    respond_to do |f|
      f.html
      f.turbo_stream
    end
  end

  def boards_added_by_owner
    boards = @pin.owner_public_boards
    @pagy, @boards = pagy(boards)
    respond_to do |f|
      f.html
      f.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pin_params
    params.require(:pin).permit(:name, :address, :latitude, :longitude,
                                :cover_photo_description, :cover_photo, :description, :tag_list,
                                cover_photo_crop_attributes: %i[crop_x crop_y crop_width crop_height])
  end

  def authorize_pin
    authorize @pin || Pin.new
  end

  def pagy_pins_latest(vars = {})
    pagy = Pagy::Countless.new(page: params[:page], countless_minimal: true, **vars)
    [pagy, Pins::Latest.call(user: current_user, pagy:)]
  end
end

app/helpers/pins_helper.rb
# frozen_string_literal: true

module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(pin, data: { controller: 'pin', action: 'google-maps-callback@window->pin#initMap', 'pin-latitude-value': pin.latitude, 'pin-longitude-value': pin.longitude }, html: { class: 'pin-form' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address, as: :search, input_html: { data: { 'pin-target': 'field' , action: 'keydown->pin#keydown' }} %>
    <div class="map" data-pin-target="map"></div>
    <div class="field"
      data-controller='instant-upload cropper'
      data-cropper-model-value='pin'
      data-cropper-crop-model-value='cover_photo_crop'>
      <%= f.hidden_field :cover_photo, value: f.object.cover_photo.signed_id, src: url_for(f.object.cover_photo), input_html: { 'data-instant-upload-target': 'input', 'data-action': 'instant-upload#changed' } if f.object.cover_photo.attached? %>
      <%= f.input :cover_photo, as: :file, input_html: { 'data-instant-upload-target': 'input',
            'data-action': 'instant-upload#changed' } %>
      <% if f.object.cover_photo.attached? %>
        <div class="form-text cover-photo-text"><%= "#{t('photo.photo_name')}: " %> <%= f.object.cover_photo.blob.filename.to_s  %>. <%= t('photo.change_photo_info') %></div>
      <% end %>
      <p class="selected-image-area">
        <%= cl_image_tag pin.cover_photo.key,
                         transformation: [pin.cover_photo_crop_constraints],
                         quality: 'auto',
                         flags: 'progressive',
                         class: 'cover-photo responsive',
                        'data-instant-upload-target': 'image',
                        'data-cropper-target': 'image',
                        'data-action': 'instant-uploaded->cropper#changed' if pin.cover_photo.attached? && (pin.errors.blank? || !pin.cover_photo.changed?) %>

        <%= content_tag :img, nil, class: 'cover-photo responsive',
              'data-instant-upload-target': 'image',
              'data-cropper-target': 'image',
              'data-action': 'instant-uploaded->cropper#changed load->cropper#changed',
              src: url_for(pin.cover_photo.attached? ? f&.object&.cover_photo : '') if (!pin.cover_photo.attached? || pin.errors.present?) && (pin.cover_photo.changed? || pin.new_record? || pin.cover_photo&.url.blank?) %>
      </p>
    </div>
    <%= f.input :cover_photo_description, input_html: { style: 'height: 120px;' } %>
    <%= f.input :tag_list, placeholder: t('.tag_list.placeholder'),
                           hint: t('.tag_list.hint'),
                           input_html: { value: f.object.tag_list.to_s } %>
    <%= f.input :description, as: :rich_text_area, input_html: { class: 'trix-content', data: { controller: "trix", 'sgid-not-found-message': t('embeds.sgid_not_found_message'), 'embed-button-name': t('embeds.embed_button_name'), 'embed-dialog-input-placeholder': t('embeds.embed_dialog_input_placeholder'), 'embed-dialog-add-button': t('embeds.embed_dialog_add_button') } } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn_1 rounded' %>
  </div>
<% end %>

app/views/pins/boards_added_by_owner.html.erb
<%= turbo_frame_tag "tf_pin_boards_added_by_owner_#{dom_id(@pin)}" do %>
  <div id="pin_boards_added_by_owner_body_<%= dom_id(@pin) %>">
    <%= render(Boards::BoardComponent.with_collection(@boards, options: {
                                                                  current_user: current_user,
                                                                  first_twin_button_class: 'btn_1 rounded xsmall outline',
                                                                  second_twin_button_class: 'btn_1 rounded xsmall'
                                                                })) %>
  </div>
  <%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, record: @pin)) %>
<% end %>

app/views/pins/boards_added_by_owner.turbo_stream.erb
<%= turbo_stream.append "pin_boards_added_by_owner_body_#{dom_id(@pin)}" do %>
  <%= render(Boards::BoardComponent.with_collection(@boards, options: {
                                                                current_user: current_user,
                                                                first_twin_button_class: 'btn_1 rounded xsmall outline',
                                                                second_twin_button_class: 'btn_1 rounded xsmall'
                                                              })) %>
<% end %>
<%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, record: @pin, format: :turbo_stream)) %>

app/views/pins/destroy.turbo_stream.erb
<%= turbo_stream.update('toastr', partial: 'shared/toastr', formats: [:turbo_stream]) %>
<%= turbo_stream.remove(@pin) %>

<%= turbo_stream.replace "pins_link_#{dom_id(@pin.user)}" do %>
  <%= render(Profiles::PinsLinkComponent.new(user: @pin.user)) %>
<% end %>

app/views/pins/edit.html.erb
<% title t('.title') %>
<% set_meta_tags alternate: { "en" => edit_pin_url(@pin, locale: :en),
                              "tr" => edit_pin_url(@pin, locale: :tr) } %>
<div class="container margin_100_55 col-lg-5">
  <%= render 'form', pin: @pin %>
</div>

app/views/pins/index.html.erb
<% title t('home') %>
<% set_meta_tags alternate: { "en" => pins_url(locale: :en),
                              "tr" => pins_url(locale: :tr) },
                 description: t('home_page_description'),
                 keywords: t('home_page_keywords') %>
<% set_meta_tags og: {
      type:     'website',
      title: "#{t('home')} - Pinmapper",
      description: t('pinmapper_slogan'),
      site: :site,
      image:    "https://res.cloudinary.com/pinmapper/image/upload/og_card_#{locale}.png",
      url: pins_url
    } %>
<% set_meta_tags twitter: {
      card: "summary_large_image",
      title: "#{t('home')} - Pinmapper",
      description: t('pinmapper_slogan'),
      site: :site,
      image:    "https://res.cloudinary.com/pinmapper/image/upload/og_card_#{locale}.png",
      url: pins_url
    } %>

<div class="container margin_100_55 pins-index">
  <% if @pins.any? %>
    <div id="infinite-pins" class="row infinite-pins">
      <%= render(Pins::PinComponent.with_collection(@pins, current_user: current_user)) %>
      <!-- /pin_lists -->
    </div>
    <%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, records: @pins)) %>
    <!-- /row -->
  <% else %>
    <div class="empty-message responsive">
      <%= image_tag 'https://res.cloudinary.com/pinmapper/image/upload/pins-empty-image.png', class: "responsive", alt: '' %>
      <p><%= sanitize t('.empty_message', explore_link: link_to(t('explore.explore'), explore_index_path, class: 'black-link')) %></p>
    </div>
  <% end %>
</div>
<!-- /container -->

app/views/pins/index.turbo_stream.erb
<%= turbo_stream.append "infinite-pins" do %>
  <%= render(Pins::PinComponent.with_collection(@pins, current_user: current_user)) %>
<% end %>
<%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, records: @pins, format: :turbo_stream)) %>

app/views/pins/like.html.erb
<%= render Pins::LikeButtonComponent.new(pin: @pin, current_user: current_user) %>

app/views/pins/liked_pins.html.erb
<% set_meta_tags alternate: { "en" => liked_pins_pins_url(locale: :en),
                              "tr" => liked_pins_pins_url(locale: :tr) } %>
<div class="container margin_100_55">
  <div class="row">
    <div class="col-lg-12 liked-pins">
      <div class="header">
        <div class="main_title_3 small-h1">
          <span><em></em></span>
          <div class="title"><h1><%= title t('liked_pins') %></h1><div class="count"><%= "(#{@pagy.count})" %></div></div>
        </div>
      </div>
      <% if @pins.any? %>
        <div id="infinite-pins" class="infinite-pins">
          <%= render(Pins::PinComponent.with_collection(@pins, current_user: current_user)) %>
          <!-- /pin_lists -->
        </div>
        <%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy)) %>
      <% else %>
        <div class="no-data">
          <p><%= t('.no_data') %></p>
        <div>
      <% end %>
    </div>
  </div>
</div>
<!-- /container -->

app/views/pins/liked_pins.turbo_stream.erb
<%= turbo_stream.append "infinite-pins" do %>
  <%= render(Pins::PinComponent.with_collection(@pins, current_user: current_user)) %>
<% end %>
<%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, format: :turbo_stream)) %>

app/views/pins/new.html.erb
<% title t('.title') %>
<% set_meta_tags alternate: { "en" => new_pin_url(locale: :en),
                              "tr" => new_pin_url(locale: :tr) } %>
<div class="container margin_100_55 col-lg-5">
  <%= render 'form', pin: @pin %>
<div>

app/views/pins/show.html.erb
<% keywords = "#{@pin.cached_tag_list}, #{t('pin_base_keywords')}" %>
<% set_meta_tags alternate: { "en" => pin_url(@pin, locale: :en),
                              "tr" => pin_url(@pin, locale: :tr) },
                 description: @pin.cover_photo_description.presence || @pin.description&.body&.to_plain_text,
                 keywords: keywords.split(', ').uniq.join(', ') %>
<% og = {
      type:     'website',
      title: "#{@pin.name} - Pinmapper",
      description: @pin.cover_photo_description.presence || @pin.description&.body&.to_plain_text,
      site: :site,
      url: pin_url(@pin)
   } %>
<% twitter = {
      card: "summary_large_image",
      title: "#{@pin.name} - Pinmapper",
      description: @pin.cover_photo_description.presence || @pin.description&.body&.to_plain_text,
      site: :site,
      url: pin_url(@pin)
   } %>
<% image = cloudinary_url(@pin.cover_photo.key, transformation: [@pin.cover_photo_crop_constraints], quality: 'auto', flags: 'progressive') if @pin.cover_photo.present? %>
<% if image.blank? %>
  <% first_image = @pin&.description&.embeds&.find { |embeds| embeds.image? } %>
  <% image = cloudinary_url(first_image.blob.key) if first_image.present? %>
<% end %>
<% if image.present? %>
  <% og[:image] = image %>
  <% twitter[:image] = image %>
<% end %>
<% set_meta_tags og: og %>
<% set_meta_tags twitter: twitter %>

<div class="container margin_100_55 pin-show">
  <div class="row">
    <div class="col-lg-9">
      <div class="pin-show-main">
        <div class="header">
          <div class="hrow">
            <div class="hrow">
              <% user_profile = @pin.user.profile %>
              <%= render(Profiles::AvatarComponent.new(src: cloudinary_url(user_profile.avatar.key, transformation: [user_profile.avatar_crop_constraints, { width: 200, height: 200, crop: 'fill' }], quality: 'auto', flags: 'progressive'))) %>
              <div class="vcolumn">
                <%= link_to @pin.user.username, profile_path(@pin.user), class: 'username' %>
                <small class="creation-time"><%= l(@pin.created_at) %></small>
              </div>
            </div>
            <div class="hrow">
              <%= render Pins::Boards::AddToBoardButtonComponent.new(pin: @pin, current_user: current_user) %>
              <%= render Pins::LikeButtonComponent.new(pin: @pin, current_user: current_user) %>
            </div>
          </div>
          <div class="address"><i class="icon_pin_alt"></i>
            <span><%= link_to @pin.city_country, explore_location_path(@pin.token), class: 'black-link-555' %></span>
          </div>
          <div class="hrow nowrap">
            <h1><%= title @pin.name %></h1>
            <%= render(Pins::MoreButtonComponent.new(pin: @pin, current_user: current_user, turbo: false)) %>
          </div>
          <div class="hrow negative-margin-top">
            <div class="tags"><%= render(Taggable::TagListComponent.new(tags: @pin.tags)) %></div>
          </div>
        </div>
        <div data-controller="gallery">
          <%= @pin.description %>
        </div>
        <div><%= render Pins::Boards::AddedByOwnerComponent.new(pin: @pin, current_user: @current_user) %></div>
      </div>
    </div>

    <aside class="col-lg-3 widgets">
      <% marker_service = MapServices::GenerateMarkers::Pin.call(@pin) %>
      <% if marker_service[:success] && marker_service[:payload].present? %>
        <div class="map-widget widget">
          <%= render(General::MapComponent.new(markers: marker_service[:payload])) %>
        </div>
      <% end %>
      <% nearby_pins = @pin.geocode.present? && @pin.nearbys(1).limit(3) %>
      <% if nearby_pins.present? %>
        <div class="widget">
          <div class="widget-title">
            <h4><%= t('.nearby_pins') %></h4>
          </div>
          <ul class="pins-list">
            <%= render(Pins::PinListItemComponent.with_collection(nearby_pins)) %>
          </ul>
        </div>
      <% end %>
    </aside>
  </div>
</div>

app/views/pins/unlike.html.erb
<%= render Pins::LikeButtonComponent.new(pin: @pin, current_user: current_user) %>