config/routes.rb
Rails.application.routes.draw do
  get '/:sitemap', to:          'sitemaps#show',
                   constraints: { format: /xml/, sitemap: /sitemap-.+/ }
  require 'sidekiq/web'
  get '/robots.:format', to: 'pages#robots'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :embed, only: :update
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all

    unauthenticated do
      root 'explore#index'
    end

    authenticated :user do
      root 'pins#index', as: :authenticated_root
    end
    get 'terms_of_use' => 'pages#terms_of_use'
    get 'privacy_policy' => 'pages#privacy_policy'
    get 'about' => 'pages#about'
    get 'cookie_policy' => 'pages#cookie_policy'
    devise_for :users, skip: %i[registrations omniauth_callbacks]
    # devise/registrations#edit route'unu iptal etmek için aşağıdaki block eklendi
    as :user do
      get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get 'users/sign_up' => 'devise/registrations#new', as: 'new_user_registration'
      patch 'users' => 'devise/registrations#update', as: 'user_registration'
      put 'users' => 'devise/registrations#update'
      delete 'users' => 'devise/registrations#destroy'
      post 'users' => 'devise/registrations#create'
    end
    # search
    get 'search/pins'
    get 'search/boards'
    get 'search/users'
    # explore
    get 'explore/index'
    get 'explore/locations/:token' => 'explore#location', as: :explore_location
    # settings
    get 'settings/edit_profile'
    get 'settings/change_password'
    get 'settings/change_username'
    get 'settings/change_email'
    get 'settings/switch_locale'
    get 'settings/accept_cookies'
    namespace :settings do
      put 'profiles/update'
      put 'users/change_password'
      put 'users/change_username'
      put 'users/change_email'
    end
    resources :boards do
      member do
        get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
        get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
        get 'follow'
        get 'unfollow'
        patch 'move/:pin_id', action: 'move', as: 'move_pin'
        patch 'move_board_by_id'
        patch 'move_board_section/:board_section_id', action: 'move_board_section',
                                                      as:     'move_board_section'
        get 'add_to_board_section_list'
        get 'select_boards'
        get 'autocomplete'
        get 'merge'
      end
      collection do
        get 'add_to_board_list/:pin_id', action: 'add_to_board_list', as: 'add_to_board_list'
        get 'following_boards'
      end
      resources :board_sections, shallow: true, except: %i[index] do
        member do
          get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
          get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
          patch 'move'
          patch 'move_pin/:pin_id', action: 'move_pin', as: 'move_pin'
          get 'select_board_sections'
          get 'autocomplete'
          get 'merge'
        end
      end
    end
    resources :tags, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
      end
      collection do
        get 'following_tags'
      end
    end
    resources :profiles, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
        get 'followers'
        get 'following'
        get 'boards'
      end
    end
    resources :pins do
      member do
        get 'like'
        get 'unlike'
        get 'boards_added_by_owner'
      end
      collection do
        get 'liked_pins'
      end
    end
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  include Pagy::Backend

  def pins
    pins = Pin.pg_search(params[:q]).order(created_at: :desc)
    @pagy, @pins = pagy pins
  end

  def boards
    boards = Board.pg_search(params[:q])
    boards = if current_user.present?
               boards.where('user_id != ? AND privacy = 0 OR user_id = ?',
                            current_user.id,
                            current_user.id)
             else
               boards.public_privacy
             end.order(created_at: :desc)
    @pagy, @boards = pagy boards
  end

  def users
    users = User.pg_search(params[:q]).order(created_at: :desc)
    @pagy, @users = pagy users
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/views/search/_sidemenu.html.erb
<% title t('search.title', keyword: params[:q]) %>
<ul class="list-group">
  <%= link_to t('search.pins'), search_pins_path(q: params[:q]), title: t('search.pins'), class: "black-link list-group-item list-group-item-action #{:pins == page ? 'active' : ''}" %>
  <%= link_to t('search.boards'), search_boards_path(q: params[:q]), title: t('search.boards'), class: "black-link list-group-item list-group-item-action #{:boards == page ? 'active' : ''}" %>
  <%= link_to t('search.users'), search_users_path(q: params[:q]), title: t('search.users'), class: "black-link list-group-item list-group-item-action #{:users == page ? 'active' : ''}" %>
</ul>

app/views/search/boards.html.erb
<% set_meta_tags alternate: { "en" => search_boards_url(locale: :en),
                              "tr" => search_boards_url(locale: :tr) } %>
<div class="container margin_100_55 search">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('search.results') %></h2>
    </div>
  </div>
    <div class="row">
    <div class="col-lg-3 search-sidemenu">
      <%= render 'search/sidemenu', page: :boards %>
    </div>
    <div class="col-lg-9 search-main">
      <div class="body">
        <% if @boards.present? %>
          <div id="boards" class="row">
            <%= render(Boards::BoardComponent.with_collection(@boards, options: { current_user: current_user })) %>
          </div>
          <%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy)) %>
        <% else %>
          <div class="row">
            <p class="no-results-found"><%= t('search.no_results_found') %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/boards.turbo_stream.erb
<%= turbo_stream.append "boards" do %>
  <%= render(Boards::BoardComponent.with_collection(@boards, options: { current_user: current_user })) %>
<% end %>
<%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, format: :turbo_stream)) %>

app/views/search/pins.html.erb
<% set_meta_tags alternate: { "en" => search_pins_url(locale: :en),
                              "tr" => search_pins_url(locale: :tr) } %>
<div class="container margin_100_55 search">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('search.results') %></h2>
    </div>
  </div>
    <div class="row">
    <div class="col-lg-3 search-sidemenu">
      <%= render 'search/sidemenu', page: :pins %>
    </div>
    <div class="col-lg-9 search-main">
      <div class="body">
        <% if @pins.present? %>
          <div id="infinite-pins" class="row infinite-pins">
            <%= render(Pins::PinComponent.with_collection(@pins, current_user: current_user)) %>
          </div>
          <%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy)) %>
        <% else %>
          <div class="row">
            <p class="no-results-found"><%= t('search.no_results_found') %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/pins.turbo_stream.erb
<%= turbo_stream.append "infinite-pins" do %>
  <%= render(Pins::PinComponent.with_collection(@pins, current_user: current_user)) %>
<% end %>
<%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, format: :turbo_stream)) %>

app/views/search/users.html.erb
<% set_meta_tags alternate: { "en" => search_users_url(locale: :en),
                              "tr" => search_users_url(locale: :tr) } %>
<div class="container margin_100_55 search">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('search.results') %></h2>
    </div>
  </div>
    <div class="row">
    <div class="col-lg-3 search-sidemenu">
      <%= render 'search/sidemenu', page: :users %>
    </div>
    <div class="col-lg-9 search-main">
      <div class="body">
        <% if @users.present? %>
          <div id="users" class="row">
            <%= render(Profiles::FollowUserListItemComponent.with_collection(@users, current_user: current_user)) %>
          </div>
          <%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy)) %>
        <% else %>
          <div class="row">
            <p class="no-results-found"><%= t('search.no_results_found') %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/users.turbo_stream.erb
<%= turbo_stream.append "users" do %>
  <%= render(Profiles::FollowUserListItemComponent.with_collection(@users, current_user: current_user)) %>
<% end %>
<%= render(General::InfiniteScrollPagyComponent.new(pagy: @pagy, format: :turbo_stream)) %>