config/routes.rb
Rails.application.routes.draw do
  get '/:sitemap', to:          'sitemaps#show',
                   constraints: { format: /xml/, sitemap: /sitemap-.+/ }
  require 'sidekiq/web'
  get '/robots.:format', to: 'pages#robots'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :embed, only: :update
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all

    unauthenticated do
      root 'explore#index'
    end

    authenticated :user do
      root 'pins#index', as: :authenticated_root
    end
    get 'terms_of_use' => 'pages#terms_of_use'
    get 'privacy_policy' => 'pages#privacy_policy'
    get 'about' => 'pages#about'
    get 'cookie_policy' => 'pages#cookie_policy'
    devise_for :users, skip: %i[registrations omniauth_callbacks]
    # devise/registrations#edit route'unu iptal etmek için aşağıdaki block eklendi
    as :user do
      get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get 'users/sign_up' => 'devise/registrations#new', as: 'new_user_registration'
      patch 'users' => 'devise/registrations#update', as: 'user_registration'
      put 'users' => 'devise/registrations#update'
      delete 'users' => 'devise/registrations#destroy'
      post 'users' => 'devise/registrations#create'
    end
    # search
    get 'search/pins'
    get 'search/boards'
    get 'search/users'
    # explore
    get 'explore/index'
    get 'explore/locations/:token' => 'explore#location', as: :explore_location
    # settings
    get 'settings/edit_profile'
    get 'settings/change_password'
    get 'settings/change_username'
    get 'settings/change_email'
    get 'settings/switch_locale'
    get 'settings/accept_cookies'
    namespace :settings do
      put 'profiles/update'
      put 'users/change_password'
      put 'users/change_username'
      put 'users/change_email'
    end
    resources :boards do
      member do
        get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
        get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
        get 'follow'
        get 'unfollow'
        patch 'move/:pin_id', action: 'move', as: 'move_pin'
        patch 'move_board_by_id'
        patch 'move_board_section/:board_section_id', action: 'move_board_section',
                                                      as:     'move_board_section'
        get 'add_to_board_section_list'
        get 'select_boards'
        get 'autocomplete'
        get 'merge'
      end
      collection do
        get 'add_to_board_list/:pin_id', action: 'add_to_board_list', as: 'add_to_board_list'
        get 'following_boards'
      end
      resources :board_sections, shallow: true, except: %i[index] do
        member do
          get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
          get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
          patch 'move'
          patch 'move_pin/:pin_id', action: 'move_pin', as: 'move_pin'
          get 'select_board_sections'
          get 'autocomplete'
          get 'merge'
        end
      end
    end
    resources :tags, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
      end
      collection do
        get 'following_tags'
      end
    end
    resources :profiles, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
        get 'followers'
        get 'following'
        get 'boards'
      end
    end
    resources :pins do
      member do
        get 'like'
        get 'unlike'
        get 'boards_added_by_owner'
      end
      collection do
        get 'liked_pins'
      end
    end
  end
end

app/views/shared/_cookies_bar.html.erb
<% if !current_user&.cookies_confirmation_status_accepted? && cookies[:allow_cookies].blank? %>
  <div id="cookies-bar" class="cookies-bar" data-controller="cookie-bar">
    <p>
      <%= sanitize t('shared.footer.cookies_bar_message',
                            privacy_policy: link_to(t('shared.footer.privacy_policy'), privacy_policy_path),
                            terms_of_use: link_to(t('shared.footer.terms_of_use'), terms_of_use_path),
                            cookie_policy: link_to(t('shared.footer.cookie_policy'), cookie_policy_path)) %>
    </p>
    <% if current_user.present? %>
      <%= link_to t('done'), settings_accept_cookies_path,
                            class: 'btn_1',
                            data: { action: 'click->cookie-bar#allowCookies', 'turbo-stream': true } %>
    <% else %>
      <button type="button" class="btn_1" data-action="click->cookie-bar#allowCookies"><%= t('done') %></button>
    <% end %>
  </div>
<% end %>

app/views/shared/_copy.html.erb
© <%= Time.zone.now.year %> Pinmapper

app/views/shared/_footer.html.erb
<footer>
  <div class="container margin_60_35">
    <div class="row columns">
      <div>
        <%= link_to root_path do %>
          <%= inline_svg_pack_tag 'media/images/logo.svg', width: '150px', height: '36px', class: 'logo' %>
        <% end %>
        <ul class="links">
          <li><%= link_to t('.about'), about_path %></li>
        </ul>
      </div>
      <div>
        <h5><%= t('.follow_us') %></h5>
        <div class="follow_us">
          <ul>
            <li><a href="https://twitter.com/pinmapper"><i class="ti-twitter-alt"></i></a></li>
            <li><a href="https://www.instagram.com/pinmapper"><i class="ti-instagram"></i></a></li>
          </ul>
        </div>
      </div>
      <div>
        <h5><%= t('.contant_with_us') %></h5>
        <ul class="contacts">
          <li><a href="mailto:hello@pinmapper.com"><i class="ti-email"></i> hello@pinmapper.com</a></li>
        </ul>
      </div>
    </div>
    <!--/row-->
    <hr>
    <div class="row">
      <div class="col-lg-6">
        <ul id="footer-selector">
          <li>
            <div class="dropdown show dropdown-lang">
              <a class="btn btn-secondary btn-sm dropdown-footer" href="#" role="button" id="dropdownLang" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= I18n.locale == :tr ? "Türkçe" : "English" %>
                <i class="fa fa-globe"></i>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownLang">
                <%= link_to "Türkçe", current_user.present? ? settings_switch_locale_path(locale: :tr) : { locale: :tr }, class: 'dropdown-item' %>
                <%= link_to "English", current_user.present? ? settings_switch_locale_path(locale: :en) : { locale: :en }, class: 'dropdown-item' %>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul id="additional_links">
          <li><%= link_to t('.terms_of_use'), terms_of_use_path %></li>
          <li><%= link_to t('.privacy_policy'), privacy_policy_path %></li>
          <li><span><%= render 'shared/copy' %></span></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!--/footer-->

app/views/shared/_google_tag_manager_body.html.erb
<% if Rails.env.production? %>
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= Rails.application.credentials.dig(:google, :tag_manager, :container_id) %>"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
<% end %>

app/views/shared/_google_tag_manager_head.html.erb
<% if Rails.env.production? %>
  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer',"<%= Rails.application.credentials.dig(:google, :tag_manager, :container_id) %>");</script>
  <!-- End Google Tag Manager -->
<% end %>

app/views/shared/_header.html.erb
<header class="header sticky menu_fixed">
  <div class="container">
    <%= link_to root_path do %>
      <%= inline_svg_pack_tag 'media/images/logo-sticky.svg', class: 'logo_sticky', width: '150px', height: '36px' %>
    <% end %>
    <%= render 'shared/search_box' %>
    <div class="btn_mobile">
      <div class="hamburger hamburger--spin-r" id="hamburger">
        <div class="hamburger-box">
          <div class="hamburger-inner"></div>
        </div>
      </div>
    </div>
    <nav class="main-menu">
      <ul class="nav-menu">
        <% if user_signed_in? %>
          <div class="header-avatar not-clickable">
            <%= render(Profiles::AvatarComponent.new(src: cloudinary_url(current_user.profile.avatar.key, transformation: [current_user.profile.avatar_crop_constraints, { width: 200, height: 200, crop: 'fill' }], quality: 'auto', flags: 'progressive'), size: 32)) %>
          </div>
          <li class="visible-menu-item">
            <%= link_to t('pins.new.create_pin'), new_pin_path, class: 'btn_1' %>
          </li>
        <% end %>
        <li class="visible-menu-item">
          <% if current_user.present? %>
            <span class="item"><%= link_to t('home'), pins_path, title: t('home') %></span>
          <% end %>
          <span class="item"><%= link_to t('explore.explore'), explore_index_path, title: t('explore.explore') %></span>
        </li>
        <% if user_signed_in? %>
          <div class="user-menu">
            <li>
              <%= link_to t('profile'), profile_path(current_user), title: t('profile') %>
            </li>
            <li>
              <%= link_to t('liked_pins'), liked_pins_pins_path, title: t('liked_pins') %>
            </li>
            <li>
              <%= link_to t('following_tags'), following_tags_tags_path, title: t('following_tags') %>
            </li>
            <li>
              <%= link_to t('boards.boards'), boards_path, title: t('boards.boards') %>
            </li>
            <li>
              <%= link_to t('boards.following_boards.title'), following_boards_boards_path, title: t('boards.following_boards.title') %>
            </li>
            <li>
              <%= link_to t('settings.settings'), settings_edit_profile_path, title: t('settings.settings') %>
            </li>
            <li>
              <%= button_to t('devise.sign_out'), destroy_user_session_path, method: :delete, title: t('devise.sign_out'), class: 'dropdown-item', data: { turbo: false } %>
            </li>
          </div>
        <% end %>
        <% if user_signed_in? %>
          <li>
            <div class="dropdown dropdown-user">
              <%= link_to '#0', class: 'logged', 'data-bs-toggle': 'dropdown', 'data-bs-offset': '0, 5', title: current_user.username do %>
                <div class="header-avatar">
                  <%= render(Profiles::AvatarComponent.new(src: cloudinary_url(current_user.profile.avatar.key, transformation: [current_user.profile.avatar_crop_constraints, { width: 200, height: 200, crop: 'fill' }], quality: 'auto', flags: 'progressive'), size: 32)) %>
                </div>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end">
                <%= link_to t('profile'), profile_path(current_user), title: t('profile'), class: 'dropdown-item' %>
                <%= link_to t('liked_pins'), liked_pins_pins_path, title: t('liked_pins'), class: 'dropdown-item' %>
                <%= link_to t('following_tags'), following_tags_tags_path, title: t('following_tags'), class: 'dropdown-item' %>
                <%= link_to t('boards.boards'), boards_path, title: t('boards.boards'), class: 'dropdown-item' %>
                <%= link_to t('boards.following_boards.title'), following_boards_boards_path, title: t('boards.following_boards.title'), class: 'dropdown-item' %>
                <%= link_to t('settings.settings'), settings_edit_profile_path, title: t('settings.settings'), class: 'dropdown-item' %>
                <%= button_to t('devise.sign_out'), destroy_user_session_path, method: :delete, title: t('devise.sign_out'), class: 'dropdown-item', data: { turbo: false } %>
              </div>
            </div>
          </li>
        <% else %>
          <li class="visible-menu-item"><span>
            <%= link_to t('devise.sign_in'), new_user_session_path, id: 'sign-in', class: 'login', title: t('devise.sign_in') %>
          </span></li>
          <li class="visible-menu-item"><span>
            <%= link_to t('devise.sign_up'), new_user_registration_path, class: 'login', title: t('devise.sign_up') %>
          </span></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<!-- /header -->

app/views/shared/_search_box.html.erb
<div class="search">
  <% path = search_pins_path %>
  <% path = search_boards_path if params[:controller].eql?('search') && params[:action].eql?('boards') %>
  <% path = search_users_path if params[:controller].eql?('search') && params[:action].eql?('users') %>
  <%= form_with url: path, method: :get do |form| %>
    <%= form.text_field :q, class: 'form-control', placeholder: t('search.search'), autocomplete: 'off', value: params[:q] %>
    <%= form.button :submit do %>
      <i class='icon_search'></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_toastr.html.erb
<%= tag.script do %>
  <% flash.each do |type, message| %>
    <% next if message.blank? %>

    <%= toastr_flash_class(type.to_s) %>('<%= message %>')
  <% end %>
<% end %>

app/views/shared/_toastr.turbo_stream.erb
<%= tag.script do %>
  <% flash.each do |type, message| %>
    <% next if message.blank? %>

    <%= toastr_flash_class(type.to_s) %>('<%= message %>')
  <% end %>
<% end %>