config/routes.rb
Rails.application.routes.draw do
  get '/:sitemap', to:          'sitemaps#show',
                   constraints: { format: /xml/, sitemap: /sitemap-.+/ }
  require 'sidekiq/web'
  get '/robots.:format', to: 'pages#robots'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :embed, only: :update
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all

    unauthenticated do
      root 'explore#index'
    end

    authenticated :user do
      root 'pins#index', as: :authenticated_root
    end
    get 'terms_of_use' => 'pages#terms_of_use'
    get 'privacy_policy' => 'pages#privacy_policy'
    get 'about' => 'pages#about'
    get 'cookie_policy' => 'pages#cookie_policy'
    devise_for :users, skip: %i[registrations omniauth_callbacks]
    # devise/registrations#edit route'unu iptal etmek için aşağıdaki block eklendi
    as :user do
      get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get 'users/sign_up' => 'devise/registrations#new', as: 'new_user_registration'
      patch 'users' => 'devise/registrations#update', as: 'user_registration'
      put 'users' => 'devise/registrations#update'
      delete 'users' => 'devise/registrations#destroy'
      post 'users' => 'devise/registrations#create'
    end
    # search
    get 'search/pins'
    get 'search/boards'
    get 'search/users'
    # explore
    get 'explore/index'
    get 'explore/locations/:token' => 'explore#location', as: :explore_location
    # settings
    get 'settings/edit_profile'
    get 'settings/change_password'
    get 'settings/change_username'
    get 'settings/change_email'
    get 'settings/switch_locale'
    get 'settings/accept_cookies'
    namespace :settings do
      put 'profiles/update'
      put 'users/change_password'
      put 'users/change_username'
      put 'users/change_email'
    end
    resources :boards do
      member do
        get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
        get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
        get 'follow'
        get 'unfollow'
        patch 'move/:pin_id', action: 'move', as: 'move_pin'
        patch 'move_board_by_id'
        patch 'move_board_section/:board_section_id', action: 'move_board_section',
                                                      as:     'move_board_section'
        get 'add_to_board_section_list'
        get 'select_boards'
        get 'autocomplete'
        get 'merge'
      end
      collection do
        get 'add_to_board_list/:pin_id', action: 'add_to_board_list', as: 'add_to_board_list'
        get 'following_boards'
      end
      resources :board_sections, shallow: true, except: %i[index] do
        member do
          get 'add_pin/:pin_id', action: 'add_pin', as: 'add_pin'
          get 'remove_pin/:pin_id', action: 'remove_pin', as: 'remove_pin'
          patch 'move'
          patch 'move_pin/:pin_id', action: 'move_pin', as: 'move_pin'
          get 'select_board_sections'
          get 'autocomplete'
          get 'merge'
        end
      end
    end
    resources :tags, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
      end
      collection do
        get 'following_tags'
      end
    end
    resources :profiles, only: %i[show] do
      member do
        get 'follow'
        get 'unfollow'
        get 'followers'
        get 'following'
        get 'boards'
      end
    end
    resources :pins do
      member do
        get 'like'
        get 'unlike'
        get 'boards_added_by_owner'
      end
      collection do
        get 'liked_pins'
      end
    end
  end
end

app/controllers/settings/profiles_controller.rb
# frozen_string_literal: true

module Settings
  class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def update
      respond_to do |format|
        if current_user.profile.update(update_profile_params)
          flash.now[:notice] = t('.profile_updated')
          format.turbo_stream
        else
          format.html { render 'settings/edit_profile', status: :unprocessable_entity }
        end
      end
    end

    private

    def update_profile_params
      params.require(:profile)
            .permit(:bio, :avatar,
                    avatar_crop_attributes: %i[crop_x crop_y crop_width crop_height])
    end
  end
end

app/controllers/settings/users_controller.rb
# frozen_string_literal: true

module Settings
  class UsersController < ApplicationController
    before_action :authenticate_user!

    # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    def change_password
      respond_to do |format|
        if current_user.update_with_password(change_password_params)
          bypass_sign_in(current_user)
          flash.now[:notice] = t('.password_changed')
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update('change_password_form', partial: 'settings/change_password_form'),
              turbo_stream.update('toastr', partial: 'shared/toastr', formats: [:turbo_stream])
            ]
          end
        else
          format.html { render 'settings/change_password', status: :unprocessable_entity }
        end
      end
    end

    def change_username
      respond_to do |format|
        if current_user.update(change_username_params)
          flash.now[:notice] = t('.username_changed')
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update('change_username_form', partial: 'settings/change_username_form'),
              turbo_stream.update('toastr', partial: 'shared/toastr', formats: [:turbo_stream])
            ]
          end
        else
          format.html { render 'settings/change_username', status: :unprocessable_entity }
        end
      end
    end

    def change_email
      respond_to do |format|
        if current_user.update(change_email_params)
          flash.now[:notice] = t('.email_changed')
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update('change_email_form', partial: 'settings/change_email_form'),
              turbo_stream.update('toastr', partial: 'shared/toastr', formats: [:turbo_stream])
            ]
          end
        else
          format.html { render 'settings/change_email', status: :unprocessable_entity }
        end
      end
    end
    # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

    private

    def change_password_params
      params.require(:user).permit(:password, :password_confirmation, :current_password)
    end

    def change_username_params
      params.require(:user).permit(:username)
    end

    def change_email_params
      params.require(:user).permit(:email)
    end
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action :authenticate_user!

  def change_password; end

  def change_username; end

  def change_email; end

  def edit_profile; end

  def switch_locale
    current_user.update(locale: params[:locale])
    I18n.locale = params[:locale]
    redirect_to handle_url
  end

  def accept_cookies
    current_user.cookies_confirmation_status_accepted! if current_user.present?

    head :ok
  end

  private

  def start_with_available_locales_regex(available_locales)
    locales = available_locales.join('|')
    Regexp.new("\\A#{locales}")
  end

  def handle_url
    url = URI(request&.referer || '').path
    only_locales = I18n.available_locales.map { |l| "/#{l}" }
    url = "#{url}/" if only_locales.include?(url)
    available_locales = I18n.available_locales.map { |l| "/#{l}/" }
    if url.start_with?(*available_locales)
      url = url.sub(start_with_available_locales_regex(available_locales), "/#{params[:locale]}/")
    end
    url
  end
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
end

app/views/settings/_change_email_form.html.erb
<%= simple_form_for(current_user, url: settings_users_change_email_path, html: { method: :put }) do |f| %>
  <%= f.input :email, autofocus: true, input_html: { class: 'form-control', id: 'email' } %>
  <%= f.button :submit, t('update'), class: 'btn_1 rounded' %>
<% end %>

app/views/settings/_change_password_form.html.erb
<%= simple_form_for(current_user, url: settings_users_change_password_path, html: { method: :put }) do |f| %>
  <%= f.input :password, autofocus: true, input_html: { class: 'form-control', id: 'password1' }, hint: t('devise.minimum_characters', count: User.password_length.min) %>
  <%= f.input :password_confirmation, input_html: { class: 'form-control', id: 'password2' } %>
  <%= f.input :current_password, hint: t('settings.current_password_hint'), input_html: { class: 'form-control', id: 'current-password' } %>
  <%= f.button :submit, t('update'), class: 'btn_1 rounded' %>
<% end %>

app/views/settings/_change_username_form.html.erb
<%= simple_form_for(current_user, url: settings_users_change_username_path, html: { method: :put, data: { controller: 'settings' } }) do |f| %>
  <%= f.input :username, autofocus: true, input_html: { class: 'form-control', id: 'usename', 'data-action': "input->settings#fix_username", 'data-settings-target': 'username' } %>
  <%= f.button :submit, t('update'), class: 'btn_1 rounded' %>
<% end %>

app/views/settings/_edit_profile_form.html.erb
<%= simple_form_for(current_user.profile, url: settings_profiles_update_path, html: { method: :put, class: 'edit-profile-form' }) do |f| %>
  <div class="rounded-cropper"
      data-controller='instant-upload cropper'
      data-cropper-model-value='profile'
      data-cropper-crop-model-value='avatar_crop'
      data-cropper-cropper-type-value='rounded'>
      <%= f.hidden_field :avatar, value: f.object.avatar.signed_id, src: url_for(f.object.avatar), input_html: { 'data-instant-upload-target': 'input', 'data-action': 'instant-upload#changed' } if f.object.avatar.attached? %>
      <%= f.input :avatar, as: :file, input_html: { 'data-instant-upload-target': 'input',
            'data-action': 'instant-upload#changed' } %>
      <% if f.object.avatar.attached? %>
        <div class="form-text avatar-text"><%= "#{t('photo.photo_name')}: " %> <%= f.object.avatar.blob.filename.to_s  %>. <%= t('photo.change_photo_info') %></div>
      <% end %>
      <p class="selected-image-area">
        <%= cl_image_tag current_user.profile.avatar.key,
                         transformation: [current_user.profile.avatar_crop_constraints, { width: 400, height: 400, crop: 'fill' }],
                         quality: 'auto',
                         flags: 'progressive',
                         class: 'rounded-circle user-avatar responsive',
                         style: 'max-width: 400px; max-height: 400px',
                         'data-instant-upload-target': 'image',
                         'data-cropper-target': 'image',
                         'data-action': 'instant-uploaded->cropper#changed' if current_user.profile.avatar.attached? && (current_user.profile.errors.blank? || !current_user.profile.avatar.changed?) %>

        <%= content_tag :img, nil, width: 400, height: 400, style: 'visibility: hidden;',
              'data-instant-upload-target': 'image',
              'data-cropper-target': 'image',
              'data-action': 'instant-uploaded->cropper#changed load->cropper#changed',
              src: url_for((current_user.profile.avatar.attached?) ? f&.object&.avatar : '') if (!current_user.profile.avatar.attached? || current_user.profile.errors.present?) && (current_user.profile.avatar.changed? || current_user.profile.new_record? || current_user.profile.avatar&.url.blank?) %>
      </p>
  </div>
  <div data-controller="character-counter">
    <%= f.input :bio, input_html: { style: 'height: 100px;', data: { 'character-counter-target': 'input' } } %>
    <p><span data-character-counter-target="counter"></span> / 160</p>
  </div>
  <%= f.button :submit, t('update'), class: 'btn_1 rounded' %>
<% end %>

app/views/settings/_password_form.html.erb
<%= simple_form_for(current_user, url: settings_users_change_password_path, html: { method: :put }) do |f| %>
  <div class="form-group">
    <%= f.input :password, input_html: { class: 'form-control', id: 'password1' }, hint: t('devise.minimum_characters', count: User.password_length.min) %>
  </div>

  <div class="form-group">
    <%= f.input :password_confirmation, input_html: { class: 'form-control', id: 'password2' } %>
  </div>

  <div class="form-group">
    <%= f.input :current_password, hint: t('.current_password_hint'), input_html: { class: 'form-control', id: 'current-password' } %>
  </div>

  <%= f.button :submit, t('update'), class: 'btn_1 rounded' %>
<% end %>

app/views/settings/_sidemenu.html.erb
<ul class="list-group">
  <%= link_to t('settings.edit_profile'), settings_edit_profile_path, title: t('settings.edit_profile'), class: "black-link list-group-item list-group-item-action #{:edit_profile == page ? 'active' : ''}" %>
  <%= link_to t('settings.change_username'), settings_change_username_path, title: t('settings.change_username'), class: "black-link list-group-item list-group-item-action #{:change_username == page ? 'active' : ''}" %>
  <%= link_to t('settings.change_email'), settings_change_email_path, title: t('settings.change_email'), class: "black-link list-group-item list-group-item-action #{:change_email == page ? 'active' : ''}" %>
  <%= link_to t('settings.change_password'), settings_change_password_path, title: t('settings.change_password'), class: "black-link list-group-item list-group-item-action #{:change_password == page ? 'active' : ''}" %>
</ul>

app/views/settings/change_email.html.erb
<% set_meta_tags alternate: { "en" => settings_change_email_url(locale: :en),
                              "tr" => settings_change_email_url(locale: :tr) } %>
<div class="container margin_100_55 settings">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('settings.settings') %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 settings-sidemenu">
      <%= render 'settings/sidemenu', page: :change_email %>
    </div>
    <div class="col-lg-9 settings-main">
      <div class="header">
        <h1><%= title t('settings.change_email') %></h1>
      </div>
      <div class="body" id="change_email_form">
        <%= render 'settings/change_email_form' %>
      </div>
    </div>
  </div>
</div>

app/views/settings/change_password.html.erb
<% set_meta_tags alternate: { "en" => settings_change_password_url(locale: :en),
                              "tr" => settings_change_password_url(locale: :tr) } %>
<div class="container margin_100_55 settings">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('settings.settings') %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 settings-sidemenu">
      <%= render 'settings/sidemenu', page: :change_password %>
    </div>
    <div class="col-lg-9 settings-main">
      <div class="header">
        <h1><%= title t('settings.change_password') %></h1>
      </div>
      <div class="body" id="change_password_form">
        <%= render 'settings/change_password_form' %>
      </div>
    </div>
  </div>
</div>

app/views/settings/change_username.html.erb
<% set_meta_tags alternate: { "en" => settings_change_username_url(locale: :en),
                              "tr" => settings_change_username_url(locale: :tr) } %>
<div class="container margin_100_55 settings">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('settings.settings') %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 settings-sidemenu">
      <%= render 'settings/sidemenu', page: :change_username %>
    </div>
    <div class="col-lg-9 settings-main">
      <div class="header">
        <h1><%= title t('settings.change_username') %></h1>
      </div>
      <div class="body" id="change_username_form">
        <%= render 'settings/change_username_form' %>
      </div>
    </div>
  </div>
</div>

app/views/settings/edit_profile.html.erb
<% set_meta_tags alternate: { "en" => settings_edit_profile_url(locale: :en),
                              "tr" => settings_edit_profile_url(locale: :tr) } %>
<div class="container margin_100_55 settings">
  <div class="row col-lg-9 offset-lg-3 title">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('settings.settings') %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 settings-sidemenu">
      <%= render 'settings/sidemenu', page: :edit_profile %>
    </div>
    <div class="col-lg-9 settings-main">
      <div class="header">
        <h1><%= title t('settings.edit_profile') %></h1>
      </div>
      <div class="body" id="edit_profile_form">
        <%= render 'settings/edit_profile_form' %>
      </div>
    </div>
  </div>
</div>

app/views/settings/password.html.erb
<div class="container margin_100_55">
  <div class="row col-lg-9 offset-lg-3">
    <div class="main_title_3">
      <span><em></em></span>
      <h2><%= t('settings.settings') %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 settings-sidemenu">
      <ul class="list-group">
        <%= link_to t('settings.change_password'), settings_password_path, title: t('settings.change_password'), class: 'black-link list-group-item list-group-item-action' %>
      </ul>
    </div>
    <div class="col-lg-9 settings-main">
      <div class="header">
        <h5><%= t('settings.change_password') %></h5>
      </div>
      <div class="body" id="change_password_form">
        <%= render 'settings/password_form' %>
      </div>
    </div>
  </div>
</div>